openapi: '3.0.3'
info:
  title: Maria Theresa API
  version: '1.0'
servers:
  - url: http://localhost:8080
paths:
  /v1/name:
    get:
      tags:
        - Hello
      operationId: getName
      responses:
        '200':
          description: Send out a list of firstnames
          content:
            text/plain:
              schema:
                type: string
  /v1/kammer:
    get:
      tags:
        - Hello
      operationId: getKammer
      responses:
        '200':
          description: Welcome to the chamber of secrets
          content:
            text/plain:
              schema:
                type: string
  /v1/git:
    get:
      tags:
        - Hello
      operationId: getGit
      responses:
        '200':
          description: Welcome to the git repository
          content:
            text/plain:
              schema:
                type: string
  /v1/ball:
    get:
      tags:
      - Hello
      operationId: getBall
      responses:
        '200':
          description: The ball is round
          content:
            text/plain:
              schema:
                type: string